services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]
    restart: always
