services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]
    restart: always
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local
